# Generated by Django 6.0.4 on 2026-04-26 06:27

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('icon_url', models.TextField(blank=True, null=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'shops_shopcategory',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('address_line', models.TextField()),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('google_place_id', models.CharField(blank=True, db_index=True, max_length=300, null=True)),
                ('opening_hours', models.JSONField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('active', 'Active'), ('suspended', 'Suspended'), ('closed', 'Closed')], db_index=True, default='pending', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('rating', models.FloatField(default=0)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('floor_plan_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_shops', to=settings.AUTH_USER_MODEL)),
                ('primary_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shops', to='shops.shopcategory')),
            ],
            options={
                'db_table': 'shops_shop',
            },
        ),
        migrations.CreateModel(
            name='ShopImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.TextField()),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('is_cover', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shops.shop')),
            ],
            options={
                'db_table': 'shops_shopimage',
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddIndex(
            model_name='shop',
            index=django.contrib.postgres.indexes.GistIndex(fields=['location'], name='shops_shop_locatio_4c7ada_gist'),
        ),
    ]
