# Generated by Django 6.0.4 on 2026-04-26 06:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=210, unique=True)),
                ('logo_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inventory_brand',
            },
        ),
        migrations.CreateModel(
            name='LocationNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('path', models.TextField(db_index=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='inventory.locationnode')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_nodes', to='shops.shop')),
            ],
            options={
                'db_table': 'inventory_locationnode',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=350)),
                ('description', models.TextField(blank=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('attributes', models.JSONField(default=dict)),
                ('total_stock', models.PositiveIntegerField(default=0)),
                ('low_stock_threshold', models.PositiveSmallIntegerField(default=5)),
                ('floor_label', models.CharField(blank=True, max_length=100)),
                ('aisle_label', models.CharField(blank=True, max_length=100)),
                ('shelf_label', models.CharField(blank=True, max_length=100)),
                ('bin_label', models.CharField(blank=True, max_length=100)),
                ('location_notes', models.TextField(blank=True)),
                ('location_updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.brand')),
                ('primary_location_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.locationnode')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shops.shop')),
            ],
            options={
                'db_table': 'inventory_product',
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='inventory.product')),
            ],
            options={
                'db_table': 'inventory_pricehistory',
                'ordering': ['-recorded_at'],
                'get_latest_by': 'recorded_at',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='inventory.productcategory')),
                ('shop_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shops.shopcategory')),
            ],
            options={
                'verbose_name_plural': 'product categories',
                'db_table': 'inventory_productcategory',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.productcategory'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.TextField()),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inventory.product')),
            ],
            options={
                'db_table': 'inventory_productimage',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('variant_attributes', models.JSONField()),
                ('sku_suffix', models.CharField(blank=True, max_length=50)),
                ('stock_count', models.PositiveIntegerField(default=0)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bin_label_override', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('location_node_override', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variant_overrides', to='inventory.locationnode')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='inventory.product')),
            ],
            options={
                'db_table': 'inventory_productvariant',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('change_qty', models.IntegerField()),
                ('reason', models.CharField(choices=[('sale', 'Sale'), ('restock', 'Restock'), ('adjustment', 'Manual Adjustment'), ('import', 'CSV Import'), ('damaged', 'Damaged / Lost'), ('return', 'Customer Return')], max_length=30)),
                ('reference', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.productvariant')),
            ],
            options={
                'db_table': 'inventory_stockmovement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttributeSchema',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('data_type', models.CharField(default='string', max_length=20)),
                ('is_variant', models.BooleanField(default=False)),
                ('is_filterable', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('shop_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_schemas', to='shops.shopcategory')),
            ],
            options={
                'db_table': 'inventory_attributeschema',
                'unique_together': {('shop_category', 'key')},
            },
        ),
        migrations.AddIndex(
            model_name='locationnode',
            index=models.Index(fields=['shop', 'level'], name='inventory_l_shop_id_3c2e48_idx'),
        ),
        migrations.AddIndex(
            model_name='locationnode',
            index=models.Index(fields=['parent'], name='inventory_l_parent__c3776a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['shop', 'is_active'], name='inventory_p_shop_id_97d856_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active', 'total_stock'], name='inventory_p_categor_1dea95_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['base_price'], name='inventory_p_base_pr_881ae1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('shop', 'sku')},
        ),
    ]
